version: '3.5'
services:

  traefik:
    image: traefik:v2.2
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/docker/homelab/traefik/:/etc/traefik/
    environment:
      - DNSIMPLE_OAUTH_TOKEN=$DNSIMPLE_OAUTH_TOKEN
      - DNSIMPLE_BASE_URL=$DNSIMPLE_BASE_URL

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/sonarr:/config
      - /mnt/media/TV:/tv
      - /mnt/media/Downloading:/downloads
    labels:
      - traefik.http.routers.sonarr.rule=Host(`sonarr.t.teich.network`)


  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/docker/nzbget:/config
      - /mnt/media/Downloading:/downloads
    labels:
      - traefik.http.routers.nzbget.rule=Host(`nzbget.t.teich.network`)

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/radarr:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/Downloading:/downloads
    labels:
      - traefik.http.routers.radarr.rule=Host(`radarr.t.teich.network`)
