version: '3'
services:

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    network_mode: host
    volumes:
      - /srv/docker/plex:/config
      - /tmp/transcode:/transcode
      - /mnt/media:/data

  tautulli:
    container_name: tautulli
    image: tautulli/tautulli
    restart: unless-stopped
     environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/docker/tautulli:/config
      - /srv/docker/plex/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro
    ports:
      - 8181:8181

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/sonarr:/config
      - /mnt/media/TV:/tv
      - /mnt/media/Downloading:/downloads
    ports:
      - 8989:8989

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/docker/nzbget:/config
      - /mnt/media/Downloading:/downloads
    ports:
      - 6789:6789

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/radarr:/config
      - /mnt/media/Movies:/Movies
      - /mnt/media/Downloading:/downloads
    ports:
      - 7878:7878