version: '3.5'
services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - /srv/docker/homelab/nginx/:/etc/nginx
      - /mnt/SSL/certs/*.t.teich.network/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/sonarr:/config
      - /mnt/media/TV:/tv
      - /mnt/media/Downloading:/downloads

  nzbget:
    container_name: nzbget
    image: linuxserver/nzbget
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/docker/nzbget:/config
      - /mnt/media/Downloading:/downloads

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/radarr:/config
      - /mnt/media/Movies:/movies
      - /mnt/media/Downloading:/downloads

  code-server:
    container_name: code-server
    image: linuxserver/code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - SUDO_PASSWORD=password #optional
    volumes:
      - /srv/docker/code-server/config:/config
    restart: unless-stopped

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /srv/docker/heimdall/:/config
    ports:
      - 81:80
      - 444:443
    restart: unless-stopped
